### ISSUE TITLE
having an auth token error when reverting

### ISSUE THREAD

**Issue by smithAoE** [gregstein/DE-Replays-Manager#3]
Hi,
Was trying to revert to the august patch and get an error saying :
'Downloading depot manifest...Got CDN auth token for steamcontent.com result: Fail '

![error](https://user-images.githubusercontent.com/92111285/136423253-b8625025-9135-4670-8104-c869c9ca84fd.PNG)

**Comment by gregstein** [comment]
Fixed in the latest version 
https://github.com/gregstein/DE-Replays-Manager/releases/tag/1.3.7.0

**What happened?**

Steam libraries recently received an a security update hence the failure the of downloading your depots. The new version merges those changes so you can downgrade and upgrade your depots again.
